version: '2'

services:

  tavro_db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build: ./provisioning/docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/tavro:cached
      - ./admin:/var/www/tavro:cached
      - ./logs/api:/var/www/tavro/api/app/logs:cached
      - ./logs/admin:/var/www/tavro/admin/app/logs:cached
    links:
      - tavro_db

  api:
    build:
      context: ./provisioning/docker/nginx
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached

#  admin:
#    build:
#      context: ./provisioning/docker/nginx
#    environment:
#      VIRTUAL_HOST: ${ADMIN_HOSTNAME}
#      APP_NAME: "admin"
#      WEBROOT: ${ADMIN_WEBROOT}
#      APP_ENV: ${ADMIN_ENV}
#      NGINX_PORT: ${ADMIN_PORT}
#      PHP_CONTAINER: "php"
#    links:
#      - php
#    volumes_from:
#      - php
#    volumes:
#      - ./logs/nginx/:/var/log/nginx:cached

  www:
    build:
      context: ./provisioning/docker/drupal
    environment:
      WEBROOT: ${WWW_WEBROOT}
    expose:
      - 80
    volumes:
      - ./www:/var/www/drupal
    restart: always

  elk:
    image: willdurand/elk
    environment:
      VIRTUAL_HOST: "elk.tavro.dev"
    volumes:
      - ./provisioning/docker/elk/logstash:/etc/logstash:cached
      - ./provisioning/docker/elk/logstash/patterns:/opt/logstash/patterns:cached
    volumes_from:
      - php
      - api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - tavro_db
    environment:
      PMA_HOST: tavro_db
      PMA_PORT: 3306