version: '2'

services:

  tavro_db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: ./provisioning/docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./api/api:/var/www/api
      - ./api/init.sh:/var/www/tavro/api.sh
      - ./admin/admin:/var/www/admin
      - ./admin/init.sh:/var/www/tavro/admin.sh
      - ./logs/api:/var/www/api/app/logs:cached
      - ./logs/admin:/var/www/admin/app/logs:cached
    links:
      - tavro_db

  api:
    build:
      context: ./provisioning/docker/api
    links:
      - php
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached

  admin:
    build:
      context: ./provisioning/docker/admin
    links:
      - php
    ports:
      - "81:80"
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached

#  www:
#    build:
#      context: ./provisioning/docker/drupal
#    environment:
#      WEBROOT: ${WWW_WEBROOT}
#    ports:
#      - "80:80"
#    volumes:
#      - ./www:/var/www/html
#    restart: always

  elk:
    image: willdurand/elk
    ports:
      - "8081:80"
    volumes:
      - ./provisioning/docker/elk/logstash:/etc/logstash:cached
      - ./provisioning/docker/elk/logstash/patterns:/opt/logstash/patterns:cached
    volumes_from:
      - php
      - api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - tavro_db
    environment:
      PMA_HOST: tavro_db
      PMA_PORT: 3306