version: '2'

services:

  tavro_db:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: "db.tavro.dev"
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build: ./provisioning/docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/tavro:cached
      - ./logs/symfony:/var/www/tavro/api/app/logs:cached
    links:
      - tavro_db

  nginx:
    build:
      context: ./provisioning/docker/nginx
    environment:
      VIRTUAL_HOST: ${API_HOSTNAME}
      APP_NAME: "api"
      WEBROOT: ${API_WEBROOT}
      APP_ENV: ${API_ENV}
      NGINX_PORT: ${API_PORT}
      PHP_CONTAINER: "php"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
  
  elk:
    image: willdurand/elk
    environment:
      VIRTUAL_HOST: "elk.tavro.dev"
    volumes:
      - ./provisioning/docker/elk/logstash:/etc/logstash:cached
      - ./provisioning/docker/elk/logstash/patterns:/opt/logstash/patterns:cached
    volumes_from:
      - php
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - tavro_db
    environment:
      PMA_HOST: tavro_db
      PMA_PORT: 3306
      VIRTUAL_HOST: "phpmyadmin.tavro.dev"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy