# Build a containerized application for Tavro

version: '2.1'

services:

  db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
       - ${MYSQL_PORT}
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USERNAME: ${MYSQL_USERNAME}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      tavro:
        aliases:
          - db.tavro.dev

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: "phpmyadmin"
    restart: always
    ports:
       - '8080:80'
    depends_on:
      - db
    links:
      - db
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: db #this needs to match the container_name of the db container
        UPLOAD_SIZE: ${UPLOAD_SIZE}
    networks:
      tavro:
        aliases:
          - phpmyadmin.tavro.dev

  api:
    image: "tavro/api"
    container_name: "tavro_api"
    restart: always
    ports:
       - '80:80'
    volumes:
      - /vagrant/api:/var/www/tavro:Z
    environment:
      VIRTUAL_HOST: ${API_HOSTNAME}
      VIRTUAL_PORT: ${API_PORT}
      PUID: "id -u $USER"
      PGID: "id -g $USER"
    depends_on:
      - db
    links:
      - db
    networks:
      tavro:
        aliases:
          - api.tavro.dev

networks:
  tavro:
    driver: bridge