# Build a containerized application for Tavro

version: '2.1'

services:

  db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
       - ${MYSQL_PORT}
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USERNAME: ${MYSQL_USERNAME}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: "phpmyadmin"
    restart: always
    ports:
       - '8080:80'
    depends_on:
      - db
    links:
      - db
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: db
        UPLOAD_SIZE: ${UPLOAD_SIZE}

  api:
    image: "tavro/api"
    container_name: "tavro_api"
    restart: always
    volumes:
      - ./api:/var/www/tavro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${API_HOSTNAME}
      - NGINX_PORT=${API_PORT}
    depends_on:
      - db
    links:
      - db
    command: ["sh", "/var/www/tavro/init-dev.sh"]