# Build a containerized application for Tavro

version: '2.1'

services:

  api:
    image: "tavro/api"
    container_name: "tavro_api"
    restart: always
    volumes:
      - ./api/api:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${API_HOSTNAME}
      - NGINX_PORT=${API_PORT}
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
       - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
       - ./db:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
       test: 'echo "SELECT 1" |mysql -u${MYSQL_USERNAME} -h127.0.0.1'
       interval: 1s
       retries: 120

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: "phpmyadmin"
    restart: always
    ports:
       - '8080:80'
    depends_on:
      - db
    links:
      - db
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: ${PMA_HOST}