# Build a containerized application for Tavro

version: '2.1'

services:

  php7:
    image: php:7-fpm
    container_name: "php7"
    ports:
      - "9000:9000"
    volumes:
      - ./api/api:/var/www/tavro/api
      - ./admin/admin:/var/www/tavro/admin
      - ./app:/var/www/tavro/app

  api:
    image: nginx:latest
    container_name: "tavro_api"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api/api:/var/www/tavro/api
      - ./provisioning/docker/tavro-api/conf/nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - mysql
      - php7

  mysql:
    image: mysql:5.6
    container_name: "tavro_db"
    restart: always
    ports:
       - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USERNAME: ${MYSQL_USERNAME}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: "phpmyadmin"
    restart: always
    ports:
       - '8080:80'
    hostname: "phpmyadmin"
    domainname: ${DOMAIN_NAME}
    depends_on:
      - mysql
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: ${PMA_HOST}