version: '3'

services:

  db:
    container_name: "tavro_db"
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      tavro:
        aliases:
          - db.tavro.dev

  php:
    container_name: tavro_api
    build:
      context: ./provisioning/docker/tavro-api
    volumes:
      - ./api:/var/www/tavro
      - ./logs/tavro:/var/www/tavro/api/app/logs
    networks:
      tavro:
        aliases:
          - api.tavro.dev

  nginx:
    build:
      context: ./provisioning/docker/nginx
    environment:
      HOSTNAME: ${API_HOSTNAME}
      WEBROOT: ${API_WEBROOT}
      ENV: ${API_ENV}
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
    networks:
      tavro:
        aliases:
          - nginx.tavro.dev

  elk:
    container_name: "tavro_elk"
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./provisioning/docker/elk/logstash:/etc/logstash
      - ./provisioning/docker/elk/logstash/patterns:/opt/logstash/patterns
    depends_on:
      - php
      - nginx
    networks:
      tavro:
        aliases:
          - logs.tavro.dev

networks:
  tavro:
    driver: bridge