version: '2.1'

services:

  db:
    container_name: "tavro_db"
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: ./provisioning/docker/tavro-api
    volumes:
      - ./api:/var/www/tavro/api
      - ./logs/tavro:/var/www/tavro/api/app/logs

  nginx:
    container_name: "tavro_api_nginx"
    build:
      context: ./provisioning/docker/nginx
    environment:
      HOSTNAME: ${API_HOSTNAME}
      WEBROOT: ${API_WEBROOT}
      ENV: ${API_ENV}
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx

  elk:
    container_name: "tavro_elk"
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./provisioning/docker/elk/logstash:/etc/logstash
      - ./provisioning/docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx