# Build a containerized application for Tavro

version: '2.1'

services:

  db:
    image: mysql
    container_name: "tavro_db"
    restart: always
    ports:
       - ${MYSQL_PORT}
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USERNAME: ${MYSQL_USERNAME}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      tavro:
        aliases:
          - db.tavro.dev

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: "phpmyadmin"
    restart: always
    ports:
       - '8080:80'
    depends_on:
      - db
    links:
      - db
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: db #this needs to match the container_name of the db container
        UPLOAD_SIZE: ${UPLOAD_SIZE}
    networks:
      tavro:
        aliases:
          - phpmyadmin.tavro.dev

  api:
    image: "tavro/api"
    container_name: "tavro_api"
    restart: always
    volumes:
      - ./api:/var/www/tavro
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_HOST: ${API_HOSTNAME}
      VIRTUAL_PORT: ${API_PORT}
    depends_on:
      - db
    links:
      - db
    networks:
      tavro:
        aliases:
          - api.tavro.dev

  # admin:
  #   image: "tavro/admin"
  #   container_name: "tavro_admin"
  #   restart: always
  #   volumes:
  #     - ./admin:/var/www/tavro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     VIRTUAL_HOST: ${ADMIN_HOSTNAME}
  #     VIRTUAL_PORT: ${ADMIN_PORT}
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   command: ["bash", "/var/www/tavro/init.sh", "--env", "${ADMIN_ENVIRONMENT}"]

  # app:
  #   image: "tavro/app"
  #   container_name: "tavro_app"
  #   restart: always
  #   volumes:
  #     - ./app:/var/www/tavro
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     VIRTUAL_HOST: ${APP_HOSTNAME}
  #     VIRTUAL_PORT: ${APP_PORT}

networks:
  tavro:
    driver: bridge