# Build a containerized application for Tavro

version: 1.0

services:

  api:
    image: tavro/api
    volumes:
     - ./mysite.template:/etc/nginx/conf.d/mysite.template
     - ./api/api:/var/www/tavro/api
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=${API_HOSTNAME}
     - NGINX_PORT=${API_PORT}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  api:
    image: tavro/api
    volumes:
     - ./mysite.template:/etc/nginx/conf.d/mysite.template
     - ./api:/var/www/tavro/app
    ports:
     - "80:80"
     - "3000:3000"
    environment:
     - NGINX_HOST=${APP_HOSTNAME}
     - NGINX_PORT=${APP_PORT}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  phpfpm:
      image: tavro/phpfpm
      ports:
          - '9000:9000'
      volumes:
          - ./public:/tavro

  mysql:
      image: tavro/mysql
      ports:
          - '${MYSQL_PORT}:${MYSQL_PORT}'
      volumes:
          - ./db:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      healthcheck:
         test: 'echo "SELECT 1" |mysql -u${MYSQL_USERNAME} -h127.0.0.1'
         interval: 1s
         retries: 120

  phpmyadmin:
      image: 'phpmyadmin/phpmyadmin'
      restart: always
      ports:
         - '8080:80'
      links:
          - mysql:mysql
      environment:
          MYSQL_USERNAME: ${MYSQL_USERNAME}
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
          PMA_HOST: ${PMA_HOST}