# Build a containerized application for Tavro

version: '2.1'

services:

  api:
    image: "richarvey/nginx-php-fpm"
    volumes:
      - ./provisioning/docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./api/api:/var/www/tavro/api
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${API_HOSTNAME}
      - NGINX_PORT=${API_PORT}
    command: sed 's/{{SYMFONY_CONTROLLER}}/${SYMFONY_CONTROLLER}' /etc/nginx/conf.d/nginx.conf
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  admin:
    image: "richarvey/nginx-php-fpm"
    volumes:
     - ./provisioning/docker/admin/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./api/api:/var/www/tavro/api
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=${ADMIN_HOSTNAME}
     - NGINX_PORT=${ADMIN_PORT}
    command: sed 's/{{SYMFONY_CONTROLLER}}/${SYMFONY_CONTROLLER}' /etc/nginx/conf.d/nginx.conf
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  #  app:
  #    image: tavro/app
  #    volumes:
  #     - ./provisioning/docker/api/nginx.conf:/etc/nginx/conf.d/app.conf
  #     - ./api:/var/www/tavro/app
  #    ports:
  #     - "80:80"
  #     - "3000:3000"
  #    environment:
  #     - NGINX_HOST=${APP_HOSTNAME}
  #     - NGINX_PORT=${APP_PORT}
  #    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/app.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    image: mysql
    ports:
       - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
       - ./db:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
       test: 'echo "SELECT 1" |mysql -u${MYSQL_USERNAME} -h127.0.0.1'
       interval: 1s
       retries: 120

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8080:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        PMA_HOST: ${PMA_HOST}